Repository codekeyz/pharaoh, pull requests merged in 2023-11, with the labels that each got.

#24 Fix middleware match
  lib/src/router/handler.dart
  lib/src/router/route.dart
  lib/src/router/router.dart
  pharaoh_examples/lib/route_groups/index.dart
  pharaoh_examples/pubspec.yaml
  pubspec.yaml
Labels: bug

#23 Add :put :patch :delete calls
  supertest/lib/supertest.dart
  test/http/res.json_test.dart
Labels: enhancement

#26 Tests/res.send
  analysis_options.yaml
  lib/src/http/message.dart
  lib/src/http/response.dart
  lib/src/middleware/body_parser.dart
  test/http/res.json_test.dart
  test/http/res.send_test.dart
Labels: enhancement

#30 Feature/port shell serve static to pharaoh
  lib/pharaoh.dart
  lib/src/http/request.dart
  lib/src/http/response.dart
  lib/src/middleware/body_parser.dart
  lib/src/middleware/request_logger.dart
  lib/src/pharaoh_impl.dart
  lib/src/router/route.dart
  packages/pharaoh_static/.gitignore
  packages/pharaoh_static/CHANGELOG.md
  packages/pharaoh_static/README.md
  packages/pharaoh_static/analysis_options.yaml
  packages/pharaoh_static/lib/pharaoh_static.dart
  packages/pharaoh_static/lib/src/directory_listing.dart
  packages/pharaoh_static/lib/src/static_handler.dart
  packages/pharaoh_static/lib/src/utils.dart
  packages/pharaoh_static/pubspec.yaml
  packages/pharaoh_static/pubspec_overrides.yaml
  packages/pharaoh_static/test/pharaoh_static_test.dart
  packages/supertest/.gitignore
  packages/supertest/CHANGELOG.md
  packages/supertest/README.md
  packages/supertest/analysis_options.yaml
  packages/supertest/lib/supertest.dart
  packages/supertest/pubspec.yaml
  pharaoh_examples/pubspec.yaml
  pubspec.yaml
Labels: enhancement

#34 Feature/pharaoh basic auth
  .github/workflows/dart.yml
  .github/workflows/prepare
  .pubignore
  lib/pharaoh.dart
  lib/src/http/request.dart
  lib/src/http/response.dart
  lib/src/pharaoh_impl.dart
  lib/src/router/handler.dart
  lib/src/router/route.dart
  lib/src/router/router.dart
  packages/pharaoh_basic_auth/.gitignore
  packages/pharaoh_basic_auth/.pubignore
  packages/pharaoh_basic_auth/CHANGELOG.md
  packages/pharaoh_basic_auth/LICENSE
  packages/pharaoh_basic_auth/README.md
  packages/pharaoh_basic_auth/analysis_options.yaml
  packages/pharaoh_basic_auth/example/pharaoh_basic_auth_example.dart
  packages/pharaoh_basic_auth/lib/pharaoh_basic_auth.dart
  packages/pharaoh_basic_auth/lib/src/basic_auth.dart
  packages/pharaoh_basic_auth/pubspec.yaml
  packages/pharaoh_basic_auth/pubspec_overrides.yaml
  packages/pharaoh_basic_auth/test/basic_auth_test.dart
  packages/supertest/.gitignore
  packages/supertest/CHANGELOG.md
  packages/supertest/README.md
  packages/supertest/analysis_options.yaml
  packages/supertest/lib/supertest.dart
  packages/supertest/pubspec.yaml
  packages/supertest/test/supertest_test.dart
  pharaoh_examples/pubspec.yaml
  pharaoh_examples/test/api_service_test.dart
  pubspec.yaml
  pubspec_overrides.yaml
Labels: enhancement

#29 Port shelf-static to pharaoh
  lib/pharaoh.dart
  lib/src/http/request.dart
  lib/src/http/response.dart
  lib/src/middleware/body_parser.dart
  lib/src/middleware/request_logger.dart
  lib/src/router/route.dart
  packages/pharaoh_static/.gitignore
  packages/pharaoh_static/CHANGELOG.md
  packages/pharaoh_static/README.md
  packages/pharaoh_static/analysis_options.yaml
  packages/pharaoh_static/lib/pharaoh_static.dart
  packages/pharaoh_static/lib/src/directory_listing.dart
  packages/pharaoh_static/lib/src/static_handler.dart
  packages/pharaoh_static/lib/src/utils.dart
  packages/pharaoh_static/pubspec.yaml
  packages/pharaoh_static/pubspec_overrides.yaml
  packages/pharaoh_static/test/pharaoh_static_test.dart
  pharaoh_examples/pubspec.yaml
Labels: enhancement

#35 Fix/only allow get and head
  .gitignore
  packages/pharaoh_static/README.md
  packages/pharaoh_static/example/pharaoh_static_example.dart
  packages/pharaoh_static/lib/src/directory_listing.dart
  packages/pharaoh_static/lib/src/static_handler.dart
  packages/pharaoh_static/public/dart.png
  packages/pharaoh_static/public/favicon.ico
  packages/pharaoh_static/public/index.html
Labels: bug

#36 Chores/supported shelf middlewares
  README.md
  SHELF_INTEROP.md
  packages/pharaoh_static/README.md
  pharaoh_examples/lib/shelf_middleware/cors.dart
  pharaoh_examples/lib/shelf_middleware/helmet.dart
  pharaoh_examples/pubspec.yaml
  pubspec.yaml
Labels: documentation

#38 Publish/pharaoh basic auth
  packages/pharaoh_basic_auth/README.md
  packages/pharaoh_basic_auth/pubspec.yaml
  packages/pharaoh_basic_auth/pubspec_overrides.yaml
Labels: documentation

#39 Add feature-request, pull-request & bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#41 feat: content negotiation -> res.format
  lib/src/http/response.dart
  test/http/res.format_test.dart
Labels: good first issue

#50 feat: integrate melos for workspace management
  .github/workflows/dart.yml
  .github/workflows/scripts/prepare.sh
  .gitignore
  .pubignore
  all_lint_rules.yaml
  analysis_options.yaml
  cliff.toml
  dart_test.yaml
  melos.yaml
  melos_pharaoh.iml
  packages/pharaoh/.gitignore
  packages/pharaoh/CHANGELOG.md
  packages/pharaoh/LICENSE
  packages/pharaoh/SHELF_INTEROP.md
  packages/pharaoh/example/README.md
  packages/pharaoh/lib/pharaoh.dart
  packages/pharaoh/lib/src/http/message.dart
  packages/pharaoh/lib/src/http/request.dart
  packages/pharaoh/lib/src/http/response.dart
  packages/pharaoh/lib/src/middleware/body_parser.dart
  packages/pharaoh/lib/src/middleware/request_logger.dart
  packages/pharaoh/lib/src/pharaoh_impl.dart
  packages/pharaoh/lib/src/router/handler.dart
  packages/pharaoh/lib/src/router/route.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/lib/src/shelf_interop/adapter.dart
  packages/pharaoh/lib/src/shelf_interop/shelf.dart
  packages/pharaoh/lib/src/utils/cookie_util.dart
  packages/pharaoh/lib/src/utils/exceptions.dart
  packages/pharaoh/lib/src/utils/utils.dart
  packages/pharaoh/melos_pharaoh.iml
  packages/pharaoh/pubspec.yaml
  packages/pharaoh/test/http/res.cookie_test.dart
  packages/pharaoh/test/http/res.format_test.dart
  packages/pharaoh/test/http/res.json_test.dart
  packages/pharaoh/test/http/res.send_test.dart
  packages/pharaoh/test/http/res.set_text.dart
  packages/pharaoh/test/http/res.status_test.dart
  packages/pharaoh/test/http/res.type_test.dart
  packages/pharaoh_basic_auth/analysis_options.yaml
  packages/pharaoh_basic_auth/melos_pharaoh_basic_auth.iml
  packages/pharaoh_basic_auth/pubspec.yaml
  packages/pharaoh_jwt_auth/analysis_options.yaml
  packages/pharaoh_jwt_auth/melos_pharaoh_jwt_auth.iml
  packages/pharaoh_jwt_auth/pubspec.yaml
  packages/pharaoh_static/analysis_options.yaml
  packages/pharaoh_static/melos_pharaoh_static.iml
  packages/pharaoh_static/pubspec.lock
  packages/pharaoh_static/pubspec.yaml
  packages/spookie/analysis_options.yaml
  packages/spookie/melos_spookie.iml
  packages/spookie/pubspec.lock
  packages/spookie/pubspec.yaml
  pharaoh_examples/melos_pharaoh_examples.iml
  pharaoh_examples/pubspec.lock
  pharaoh_examples/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#49 feat: add cookie support to pharaoh
  .github/workflows/dart.yml
  .github/workflows/prepare
  .gitignore
  .pubignore
  README.md
  all_lint_rules.yaml
  analysis_options.yaml
  cliff.toml
  dart_test.yaml
  melos.yaml
  packages/pharaoh/.gitignore
  packages/pharaoh/CHANGELOG.md
  packages/pharaoh/LICENSE
  packages/pharaoh/SHELF_INTEROP.md
  packages/pharaoh/example/README.md
  packages/pharaoh/lib/pharaoh.dart
  packages/pharaoh/lib/src/http/message.dart
  packages/pharaoh/lib/src/http/request.dart
  packages/pharaoh/lib/src/http/response.dart
  packages/pharaoh/lib/src/middleware/body_parser.dart
  packages/pharaoh/lib/src/middleware/request_logger.dart
  packages/pharaoh/lib/src/pharaoh_impl.dart
  packages/pharaoh/lib/src/router/handler.dart
  packages/pharaoh/lib/src/router/route.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/lib/src/shelf_interop/adapter.dart
  packages/pharaoh/lib/src/shelf_interop/shelf.dart
  packages/pharaoh/lib/src/utils/cookie_util.dart
  packages/pharaoh/lib/src/utils/exceptions.dart
  packages/pharaoh/lib/src/utils/utils.dart
  packages/pharaoh/melos_pharaoh.iml
  packages/pharaoh/pubspec.yaml
  packages/pharaoh/test/http/res.cookie_test.dart
  packages/pharaoh/test/http/res.format_test.dart
  packages/pharaoh/test/http/res.json_test.dart
  packages/pharaoh/test/http/res.send_test.dart
  packages/pharaoh/test/http/res.set_text.dart
  packages/pharaoh/test/http/res.status_test.dart
  packages/pharaoh/test/http/res.type_test.dart
  packages/pharaoh_basic_auth/analysis_options.yaml
  packages/pharaoh_basic_auth/lib/src/basic_auth.dart
  packages/pharaoh_basic_auth/melos_pharaoh_basic_auth.iml
  packages/pharaoh_basic_auth/pubspec.yaml
  packages/pharaoh_jwt_auth/analysis_options.yaml
  packages/pharaoh_jwt_auth/melos_pharaoh_jwt_auth.iml
  packages/pharaoh_jwt_auth/pubspec.yaml
  packages/pharaoh_static/analysis_options.yaml
  packages/pharaoh_static/melos_pharaoh_static.iml
  packages/pharaoh_static/pubspec.lock
  packages/pharaoh_static/pubspec.yaml
  packages/spookie/analysis_options.yaml
  packages/spookie/melos_spookie.iml
  packages/spookie/pubspec.lock
  packages/spookie/pubspec.yaml
  pharaoh_examples/melos_pharaoh_examples.iml
  pharaoh_examples/pubspec.lock
  pharaoh_examples/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#53 update docs
  README.md
Labels: documentation

#54 feat: additional request methods :head :options :patch :trace
  packages/pharaoh/lib/src/http/response.dart
  packages/pharaoh/lib/src/pharaoh_impl.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/test/http/res.send_test.dart
  packages/pharaoh/test/http/res.set_text.dart
  packages/pharaoh_basic_auth/lib/src/basic_auth.dart
  packages/pharaoh_static/lib/src/static_handler.dart
Labels: enhancement

#51 feat: add cookie-parser & session management to pharaoh
  .gitignore
  melos.yaml
  packages/pharaoh/lib/pharaoh.dart
  packages/pharaoh/lib/src/core.dart
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/http/cookie.dart
  packages/pharaoh/lib/src/http/request.dart
  packages/pharaoh/lib/src/http/response.dart
  packages/pharaoh/lib/src/http/session.dart
  packages/pharaoh/lib/src/middleware/cookie_parser.dart
  packages/pharaoh/lib/src/middleware/session_mw.dart
  packages/pharaoh/lib/src/router/handler.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/lib/src/utils/cookie_util.dart
  packages/pharaoh/lib/src/utils/utils.dart
  packages/pharaoh/melos_pharaoh.iml
  packages/pharaoh/pubspec.yaml
  packages/pharaoh/test/http/res.cookie_test.dart
  packages/pharaoh/test/http/session_test.dart
  packages/pharaoh/test/middleware/cookie_parser_test.dart
  packages/pharaoh/test/middleware/session_mw_test.dart
  packages/pharaoh/test/router/handler_test.dart
  packages/pharaoh_basic_auth/melos_pharaoh_basic_auth.iml
  packages/pharaoh_jwt_auth/melos_pharaoh_jwt_auth.iml
  packages/pharaoh_static/melos_pharaoh_static.iml
  packages/pharaoh_static/pubspec.lock
  packages/spookie/melos_spookie.iml
  packages/spookie/pubspec.lock
  packages/spookie/test/spookie_test.dart
  pharaoh_examples/lib/api_service/index.dart
  pharaoh_examples/melos_pharaoh_examples.iml
  pharaoh_examples/pubspec.lock
  pharaoh_examples/test/api_service_test.dart
  pubspec.lock
Labels: enhancement

#56 chores: improve route handling
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/http/request.dart
  packages/pharaoh/lib/src/router/handler.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/test/router/handler_test.dart
Labels: enhancement

#57 chaining should terminate if response ended
  packages/pharaoh/lib/src/router/handler.dart
  packages/pharaoh/test/router/handler_test.dart
Labels: bug

#58 chore: seperate query params from params map
  packages/pharaoh/lib/src/http/request.dart
  packages/pharaoh/test/http/req.query_test.dart
  pharaoh_examples/lib/api_service/index.dart
Labels: good first issue
