Repository codekeyz/pharaoh, pull requests merged in 2023-12, with the labels that each got.

#64 chore: update docs
  .github/workflows/dart.yml
  README.md
  melos.yaml
  packages/spanner/README.md
Labels: documentation

#66 bugfix: midleware execution order
  packages/pharaoh/lib/src/core.dart
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/http/request.dart
  packages/pharaoh/lib/src/http/response.dart
  packages/pharaoh/lib/src/middleware/body_parser.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/lib/src/router/router_contract.dart
  packages/pharaoh/lib/src/router/router_group.dart
  packages/pharaoh/lib/src/router/router_handler.dart
  packages/pharaoh/lib/src/router/router_mixin.dart
  packages/pharaoh/pubspec.yaml
  packages/pharaoh/test/http/res.status_test.dart
  packages/pharaoh/test/middleware/body_parser_test.dart
  packages/pharaoh/test/router/router_group.dart
  packages/spanner/lib/src/route/action.dart
  packages/spanner/lib/src/tree/node.dart
  packages/spanner/lib/src/tree/tree.dart
  packages/spanner/test/acceptance/request_handling_test.dart
  packages/spanner/test/fixtures/handlers.dart
Labels: bug

#70 bugfix: capture remaining parts of route as parametric route
  packages/spanner/lib/src/tree/tree.dart
  packages/spanner/test/parametric_test.dart
  pharaoh_examples/lib/serve_files_1/index.dart
Labels: bug

#81 chore: fix middleware issues & recompose interfaces
  .gitignore
  README.md
  packages/pharaoh/README.md
  packages/pharaoh/lib/src/core.dart
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/middleware/body_parser.dart
  packages/pharaoh/lib/src/middleware/cookie_parser.dart
  packages/pharaoh/lib/src/middleware/request_logger.dart
  packages/pharaoh/lib/src/middleware/session_mw.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/lib/src/router/router_contract.dart
  packages/pharaoh/lib/src/router/router_handler.dart
  packages/pharaoh/lib/src/router/router_mixin.dart
  packages/pharaoh/lib/src/shelf_interop/adapter.dart
  packages/pharaoh/pubspec.yaml
  packages/pharaoh/test/http/req.query_test.dart
  packages/pharaoh/test/http/res.cookie_test.dart
  packages/pharaoh/test/http/res.format_test.dart
  packages/pharaoh/test/http/res.json_test.dart
  packages/pharaoh/test/http/res.set_text.dart
  packages/pharaoh/test/http/res.status_test.dart
  packages/pharaoh/test/http/res.type_test.dart
  packages/pharaoh/test/middleware/body_parser_test.dart
  packages/pharaoh/test/middleware/cookie_parser_test.dart
  packages/pharaoh/test/middleware/session_mw_test.dart
  packages/pharaoh/test/router/handler_test.dart
  packages/pharaoh/test/router/router_group.dart
  packages/pharaoh_basic_auth/lib/src/basic_auth.dart
  packages/pharaoh_basic_auth/test/basic_auth_test.dart
  packages/pharaoh_jwt_auth/lib/src/pharaoh_jwt_auth_base.dart
  packages/pharaoh_jwt_auth/test/pharaoh_jwt_auth_test.dart
  packages/pharaoh_static/lib/src/static_handler.dart
  packages/pharaoh_static/pubspec.lock
  packages/spanner/lib/src/parametric/definition.dart
  packages/spanner/lib/src/route/action.dart
  packages/spanner/lib/src/tree/node.dart
  packages/spanner/lib/src/tree/tree.dart
  packages/spanner/test/acceptance/request_handling_test.dart
  packages/spanner/test/case_insensitive_test.dart
  packages/spanner/test/fixtures/handlers.dart
  packages/spanner/test/parametric_test.dart
  packages/spookie/test/spookie_test.dart
  pharaoh_examples/lib/api_service/index.dart
  pharaoh_examples/lib/route_groups/index.dart
Labels: enhancement

#83 feat: de-couple spanner from pharaoh
  packages/pharaoh/lib/pharaoh.dart
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/http/request.dart
  packages/pharaoh/lib/src/http/request_impl.dart
  packages/pharaoh/lib/src/router/router.dart
  packages/pharaoh/lib/src/router/router_contract.dart
  packages/pharaoh/lib/src/router/router_mixin.dart
  packages/pharaoh/lib/src/utils/exceptions.dart
  packages/pharaoh/lib/src/utils/utils.dart
  packages/pharaoh/test/acceptance/request_handling_test.dart
  packages/pharaoh_static/pubspec.lock
  packages/spanner/README.md
  packages/spanner/lib/src/parametric/descriptor.dart
  packages/spanner/lib/src/route/action.dart
  packages/spanner/lib/src/tree/node.dart
  packages/spanner/lib/src/tree/tree.dart
  packages/spanner/lib/src/tree/utils.dart
  packages/spanner/pubspec.yaml
  packages/spanner/test/case_insensitive_test.dart
  packages/spanner/test/fixtures/handlers.dart
  packages/spanner/test/helpers/test_utils.dart
  packages/spanner/test/parametric_test.dart
Labels: enhancement

#86 chore: de-couple response from request
  packages/pharaoh/lib/src/core.dart
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/http/response.dart
  packages/pharaoh/lib/src/http/response_impl.dart
  packages/pharaoh/lib/src/router/router_mixin.dart
  packages/pharaoh/lib/src/shelf_interop/adapter.dart
Labels: enhancement

#87 chore: code improvements
  LICENSE
  packages/pharaoh/lib/src/core.dart
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/http/response.dart
  packages/pharaoh/lib/src/http/response_impl.dart
  packages/pharaoh/lib/src/shelf_interop/adapter.dart
  packages/pharaoh/lib/src/view/view.dart
  packages/pharaoh/test/acceptance/request_handling_test.dart
  packages/pharaoh/test/core_test.dart
  packages/pharaoh/test/http/res.format_test.dart
  packages/pharaoh/test/http/res.json_test.dart
  packages/pharaoh/test/middleware/session_mw_test.dart
  packages/pharaoh_jwt_auth/lib/src/pharaoh_jwt_auth_base.dart
  packages/pharaoh_jwt_auth/test/pharaoh_jwt_auth_test.dart
  pharaoh_examples/lib/api_service/index.dart
  pharaoh_examples/test/api_service_test.dart
Labels: enhancement

#84 chore: add contributing.md file
  CONTRIBUTING.md
Labels: documentation

#94 bugfix: throw spanner validation error for parametric descriptors
  packages/pharaoh/lib/src/core_impl.dart
  packages/pharaoh/lib/src/utils/exceptions.dart
  packages/pharaoh/pubspec.yaml
  packages/pharaoh/test/acceptance/request_handling_test.dart
  packages/spanner/lib/spanner.dart
  packages/spanner/lib/src/parametric/descriptor.dart
  packages/spanner/pubspec.yaml
  packages/spanner/test/parametric_test.dart
Labels: bug

#95 chore: add more tests for spookie
  packages/pharaoh/pubspec.yaml
  packages/pharaoh_static/pubspec.lock
  packages/spanner/test/regex.txt
  packages/spookie/lib/src/http_expectation.dart
  packages/spookie/pubspec.yaml
  packages/spookie/test/spookie_test.dart
Labels: enhancement

#98 bugfix: wildcard search in node
  packages/spanner/lib/src/route/action.dart
  packages/spanner/lib/src/tree/node.dart
  packages/spanner/pubspec.yaml
  packages/spanner/test/wildcard_test.dart
Labels: bug
